cmake_policy(SET CMP0077 NEW)

if (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()

message(STATUS "LCXX Build Type: ${CMAKE_BUILD_TYPE}")

set(CMAKE_EXTRA_C_FLAGS "-fPIC -Wall -Wno-reorder -Werror")
set(CMAKE_EXTRA_CXX_FLAGS "-fPIC -Wall -Wno-reorder -Werror")

set(CMAKE_C_FLAGS "${CMAKE_EXTRA_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_EXTRA_CXX_FLAGS}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/$<CONFIG>)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/$<CONFIG>)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/$<CONFIG>)

set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "d0edc3af-4c50-42ea-a356-e2862fe7a444")

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)

set(CMAKE_CXX_MODULE_STD 1)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS 1 CACHE BOOL "No dev warnings")

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)